version: '3.1'
services:
  redis:
    image: 'redis'
    ports: 
      - 6379:6379
  mongo:
      image: 'bitnami/mongodb'
      ports: 
        - 27017:27017
      environment: 
        - MONGODB_EXTRA_DATABASES=clock_display